// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbsoztnwfupudcrhnaxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRic296dG53ZnVwdWRjcmhuYXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDI0MDgsImV4cCI6MjA2NDQ3ODQwOH0.UGZtgDrXXCMZpnC3f4InhvMoi7j-DyJwZZ5H5Y5DoDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);